/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JpaUser implements Serializable {

    private static final long serialVersionUID = -29936220;

    private Long   id;
    private String userMobile;
    private String userName;

    public JpaUser() {}

    public JpaUser(JpaUser value) {
        this.id = value.id;
        this.userMobile = value.userMobile;
        this.userName = value.userName;
    }

    public JpaUser(
        Long   id,
        String userMobile,
        String userName
    ) {
        this.id = id;
        this.userMobile = userMobile;
        this.userName = userName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserMobile() {
        return this.userMobile;
    }

    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JpaUser (");

        sb.append(id);
        sb.append(", ").append(userMobile);
        sb.append(", ").append(userName);

        sb.append(")");
        return sb.toString();
    }
}
