/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenu implements Serializable {

    private static final long serialVersionUID = 2141170864;

    private Long   menuId;
    private String name;
    private String perms;

    public SysMenu() {}

    public SysMenu(SysMenu value) {
        this.menuId = value.menuId;
        this.name = value.name;
        this.perms = value.perms;
    }

    public SysMenu(
        Long   menuId,
        String name,
        String perms
    ) {
        this.menuId = menuId;
        this.name = name;
        this.perms = perms;
    }

    public Long getMenuId() {
        return this.menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPerms() {
        return this.perms;
    }

    public void setPerms(String perms) {
        this.perms = perms;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysMenu (");

        sb.append(menuId);
        sb.append(", ").append(name);
        sb.append(", ").append(perms);

        sb.append(")");
        return sb.toString();
    }
}
