/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 角色表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRole implements Serializable {

    private static final long serialVersionUID = -2138341637;

    private Long   roleId;
    private String roleName;

    public SysRole() {}

    public SysRole(SysRole value) {
        this.roleId = value.roleId;
        this.roleName = value.roleName;
    }

    public SysRole(
        Long   roleId,
        String roleName
    ) {
        this.roleId = roleId;
        this.roleName = roleName;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRole (");

        sb.append(roleId);
        sb.append(", ").append(roleName);

        sb.append(")");
        return sb.toString();
    }
}
