/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * 系统用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUser implements Serializable {

    private static final long serialVersionUID = -294418190;

    private Long   userId;
    private String username;
    private String password;
    private String salt;
    private String state;

    public SysUser() {}

    public SysUser(SysUser value) {
        this.userId = value.userId;
        this.username = value.username;
        this.password = value.password;
        this.salt = value.salt;
        this.state = value.state;
    }

    public SysUser(
        Long   userId,
        String username,
        String password,
        String salt,
        String state
    ) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.salt = salt;
        this.state = state;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUser (");

        sb.append(userId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(salt);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
