/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.daos;


import com.test.entity.tables.JpaUser;
import com.test.entity.tables.records.JpaUserRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JpaUserDao extends DAOImpl<JpaUserRecord, com.test.entity.tables.pojos.JpaUser, Long> {

    /**
     * Create a new JpaUserDao without any configuration
     */
    public JpaUserDao() {
        super(JpaUser.JPA_USER, com.test.entity.tables.pojos.JpaUser.class);
    }

    /**
     * Create a new JpaUserDao with an attached configuration
     */
    public JpaUserDao(Configuration configuration) {
        super(JpaUser.JPA_USER, com.test.entity.tables.pojos.JpaUser.class, configuration);
    }

    @Override
    public Long getId(com.test.entity.tables.pojos.JpaUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.JpaUser> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(JpaUser.JPA_USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.JpaUser> fetchById(Long... values) {
        return fetch(JpaUser.JPA_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.test.entity.tables.pojos.JpaUser fetchOneById(Long value) {
        return fetchOne(JpaUser.JPA_USER.ID, value);
    }

    /**
     * Fetch records that have <code>user_mobile BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.JpaUser> fetchRangeOfUserMobile(String lowerInclusive, String upperInclusive) {
        return fetchRange(JpaUser.JPA_USER.USER_MOBILE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_mobile IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.JpaUser> fetchByUserMobile(String... values) {
        return fetch(JpaUser.JPA_USER.USER_MOBILE, values);
    }

    /**
     * Fetch records that have <code>user_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.JpaUser> fetchRangeOfUserName(String lowerInclusive, String upperInclusive) {
        return fetchRange(JpaUser.JPA_USER.USER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.JpaUser> fetchByUserName(String... values) {
        return fetch(JpaUser.JPA_USER.USER_NAME, values);
    }
}
