/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.daos;


import com.test.entity.tables.SysMenu;
import com.test.entity.tables.records.SysMenuRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuDao extends DAOImpl<SysMenuRecord, com.test.entity.tables.pojos.SysMenu, Long> {

    /**
     * Create a new SysMenuDao without any configuration
     */
    public SysMenuDao() {
        super(SysMenu.SYS_MENU, com.test.entity.tables.pojos.SysMenu.class);
    }

    /**
     * Create a new SysMenuDao with an attached configuration
     */
    public SysMenuDao(Configuration configuration) {
        super(SysMenu.SYS_MENU, com.test.entity.tables.pojos.SysMenu.class, configuration);
    }

    @Override
    public Long getId(com.test.entity.tables.pojos.SysMenu object) {
        return object.getMenuId();
    }

    /**
     * Fetch records that have <code>menu_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysMenu> fetchRangeOfMenuId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SysMenu.SYS_MENU.MENU_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysMenu> fetchByMenuId(Long... values) {
        return fetch(SysMenu.SYS_MENU.MENU_ID, values);
    }

    /**
     * Fetch a unique record that has <code>menu_id = value</code>
     */
    public com.test.entity.tables.pojos.SysMenu fetchOneByMenuId(Long value) {
        return fetchOne(SysMenu.SYS_MENU.MENU_ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysMenu> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SysMenu.SYS_MENU.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysMenu> fetchByName(String... values) {
        return fetch(SysMenu.SYS_MENU.NAME, values);
    }

    /**
     * Fetch records that have <code>perms BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysMenu> fetchRangeOfPerms(String lowerInclusive, String upperInclusive) {
        return fetchRange(SysMenu.SYS_MENU.PERMS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>perms IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysMenu> fetchByPerms(String... values) {
        return fetch(SysMenu.SYS_MENU.PERMS, values);
    }
}
