/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.daos;


import com.test.entity.tables.SysRoleMenu;
import com.test.entity.tables.records.SysRoleMenuRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 角色与权限关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenuDao extends DAOImpl<SysRoleMenuRecord, com.test.entity.tables.pojos.SysRoleMenu, Long> {

    /**
     * Create a new SysRoleMenuDao without any configuration
     */
    public SysRoleMenuDao() {
        super(SysRoleMenu.SYS_ROLE_MENU, com.test.entity.tables.pojos.SysRoleMenu.class);
    }

    /**
     * Create a new SysRoleMenuDao with an attached configuration
     */
    public SysRoleMenuDao(Configuration configuration) {
        super(SysRoleMenu.SYS_ROLE_MENU, com.test.entity.tables.pojos.SysRoleMenu.class, configuration);
    }

    @Override
    public Long getId(com.test.entity.tables.pojos.SysRoleMenu object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysRoleMenu> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SysRoleMenu.SYS_ROLE_MENU.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysRoleMenu> fetchById(Long... values) {
        return fetch(SysRoleMenu.SYS_ROLE_MENU.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.test.entity.tables.pojos.SysRoleMenu fetchOneById(Long value) {
        return fetchOne(SysRoleMenu.SYS_ROLE_MENU.ID, value);
    }

    /**
     * Fetch records that have <code>role_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysRoleMenu> fetchRangeOfRoleId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SysRoleMenu.SYS_ROLE_MENU.ROLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysRoleMenu> fetchByRoleId(Long... values) {
        return fetch(SysRoleMenu.SYS_ROLE_MENU.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>menu_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysRoleMenu> fetchRangeOfMenuId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SysRoleMenu.SYS_ROLE_MENU.MENU_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysRoleMenu> fetchByMenuId(Long... values) {
        return fetch(SysRoleMenu.SYS_ROLE_MENU.MENU_ID, values);
    }
}
