/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.daos;


import com.test.entity.tables.SysUserRole;
import com.test.entity.tables.records.SysUserRoleRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户与角色关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRoleDao extends DAOImpl<SysUserRoleRecord, com.test.entity.tables.pojos.SysUserRole, Long> {

    /**
     * Create a new SysUserRoleDao without any configuration
     */
    public SysUserRoleDao() {
        super(SysUserRole.SYS_USER_ROLE, com.test.entity.tables.pojos.SysUserRole.class);
    }

    /**
     * Create a new SysUserRoleDao with an attached configuration
     */
    public SysUserRoleDao(Configuration configuration) {
        super(SysUserRole.SYS_USER_ROLE, com.test.entity.tables.pojos.SysUserRole.class, configuration);
    }

    @Override
    public Long getId(com.test.entity.tables.pojos.SysUserRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysUserRole> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SysUserRole.SYS_USER_ROLE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysUserRole> fetchById(Long... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.test.entity.tables.pojos.SysUserRole fetchOneById(Long value) {
        return fetchOne(SysUserRole.SYS_USER_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysUserRole> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SysUserRole.SYS_USER_ROLE.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysUserRole> fetchByUserId(Long... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.test.entity.tables.pojos.SysUserRole> fetchRangeOfRoleId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SysUserRole.SYS_USER_ROLE.ROLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.test.entity.tables.pojos.SysUserRole> fetchByRoleId(Long... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.ROLE_ID, values);
    }
}
