/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables;


import com.test.entity.Indexes;
import com.test.entity.Keys;
import com.test.entity.Test;
import com.test.entity.tables.records.SysRoleMenuRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 角色与权限关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenu extends TableImpl<SysRoleMenuRecord> {

    private static final long serialVersionUID = 1417557165;

    /**
     * The reference instance of <code>test.sys_role_menu</code>
     */
    public static final SysRoleMenu SYS_ROLE_MENU = new SysRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysRoleMenuRecord> getRecordType() {
        return SysRoleMenuRecord.class;
    }

    /**
     * The column <code>test.sys_role_menu.id</code>. ID
     */
    public final TableField<SysRoleMenuRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "ID");

    /**
     * The column <code>test.sys_role_menu.role_id</code>. 角色ID
     */
    public final TableField<SysRoleMenuRecord, Long> ROLE_ID = createField(DSL.name("role_id"), org.jooq.impl.SQLDataType.BIGINT, this, "角色ID");

    /**
     * The column <code>test.sys_role_menu.menu_id</code>. 权限ID
     */
    public final TableField<SysRoleMenuRecord, Long> MENU_ID = createField(DSL.name("menu_id"), org.jooq.impl.SQLDataType.BIGINT, this, "权限ID");

    /**
     * Create a <code>test.sys_role_menu</code> table reference
     */
    public SysRoleMenu() {
        this(DSL.name("sys_role_menu"), null);
    }

    /**
     * Create an aliased <code>test.sys_role_menu</code> table reference
     */
    public SysRoleMenu(String alias) {
        this(DSL.name(alias), SYS_ROLE_MENU);
    }

    /**
     * Create an aliased <code>test.sys_role_menu</code> table reference
     */
    public SysRoleMenu(Name alias) {
        this(alias, SYS_ROLE_MENU);
    }

    private SysRoleMenu(Name alias, Table<SysRoleMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysRoleMenu(Name alias, Table<SysRoleMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("角色与权限关系表"));
    }

    public <O extends Record> SysRoleMenu(Table<O> child, ForeignKey<O, SysRoleMenuRecord> key) {
        super(child, key, SYS_ROLE_MENU);
    }

    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_ROLE_MENU_PRIMARY);
    }

    @Override
    public Identity<SysRoleMenuRecord, Long> getIdentity() {
        return Keys.IDENTITY_SYS_ROLE_MENU;
    }

    @Override
    public UniqueKey<SysRoleMenuRecord> getPrimaryKey() {
        return Keys.KEY_SYS_ROLE_MENU_PRIMARY;
    }

    @Override
    public List<UniqueKey<SysRoleMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<SysRoleMenuRecord>>asList(Keys.KEY_SYS_ROLE_MENU_PRIMARY);
    }

    @Override
    public SysRoleMenu as(String alias) {
        return new SysRoleMenu(DSL.name(alias), this);
    }

    @Override
    public SysRoleMenu as(Name alias) {
        return new SysRoleMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysRoleMenu rename(String name) {
        return new SysRoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysRoleMenu rename(Name name) {
        return new SysRoleMenu(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
