/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables;


import com.test.entity.Indexes;
import com.test.entity.Keys;
import com.test.entity.Test;
import com.test.entity.tables.records.TRoleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRole extends TableImpl<TRoleRecord> {

    private static final long serialVersionUID = 382216059;

    /**
     * The reference instance of <code>test.t_role</code>
     */
    public static final TRole T_ROLE = new TRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRoleRecord> getRecordType() {
        return TRoleRecord.class;
    }

    /**
     * The column <code>test.t_role.id</code>.
     */
    public final TableField<TRoleRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>test.t_role.role_name</code>.
     */
    public final TableField<TRoleRecord, String> ROLE_NAME = createField(DSL.name("role_name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>test.t_role</code> table reference
     */
    public TRole() {
        this(DSL.name("t_role"), null);
    }

    /**
     * Create an aliased <code>test.t_role</code> table reference
     */
    public TRole(String alias) {
        this(DSL.name(alias), T_ROLE);
    }

    /**
     * Create an aliased <code>test.t_role</code> table reference
     */
    public TRole(Name alias) {
        this(alias, T_ROLE);
    }

    private TRole(Name alias, Table<TRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRole(Name alias, Table<TRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TRole(Table<O> child, ForeignKey<O, TRoleRecord> key) {
        super(child, key, T_ROLE);
    }

    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_ROLE_PRIMARY);
    }

    @Override
    public UniqueKey<TRoleRecord> getPrimaryKey() {
        return Keys.KEY_T_ROLE_PRIMARY;
    }

    @Override
    public List<UniqueKey<TRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<TRoleRecord>>asList(Keys.KEY_T_ROLE_PRIMARY);
    }

    @Override
    public TRole as(String alias) {
        return new TRole(DSL.name(alias), this);
    }

    @Override
    public TRole as(Name alias) {
        return new TRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRole rename(String name) {
        return new TRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRole rename(Name name) {
        return new TRole(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
