/*
 * This file is generated by jOOQ.
 */
package com.test.entity;


import com.test.entity.tables.JpaUser;
import com.test.entity.tables.Member;
import com.test.entity.tables.Student;
import com.test.entity.tables.SysMenu;
import com.test.entity.tables.SysRole;
import com.test.entity.tables.SysRoleMenu;
import com.test.entity.tables.SysUser;
import com.test.entity.tables.SysUserRole;
import com.test.entity.tables.TPermissions;
import com.test.entity.tables.TRole;
import com.test.entity.tables.TUser;
import com.test.entity.tables.TbUser;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index JPA_USER_PRIMARY = Indexes0.JPA_USER_PRIMARY;
    public static final Index MEMBER_PRIMARY = Indexes0.MEMBER_PRIMARY;
    public static final Index STUDENT_PRIMARY = Indexes0.STUDENT_PRIMARY;
    public static final Index SYS_MENU_PRIMARY = Indexes0.SYS_MENU_PRIMARY;
    public static final Index SYS_ROLE_PRIMARY = Indexes0.SYS_ROLE_PRIMARY;
    public static final Index SYS_ROLE_MENU_PRIMARY = Indexes0.SYS_ROLE_MENU_PRIMARY;
    public static final Index SYS_USER_PRIMARY = Indexes0.SYS_USER_PRIMARY;
    public static final Index SYS_USER_ROLE_PRIMARY = Indexes0.SYS_USER_ROLE_PRIMARY;
    public static final Index TB_USER_PRIMARY = Indexes0.TB_USER_PRIMARY;
    public static final Index T_PERMISSIONS_PRIMARY = Indexes0.T_PERMISSIONS_PRIMARY;
    public static final Index T_ROLE_PRIMARY = Indexes0.T_ROLE_PRIMARY;
    public static final Index T_USER_PRIMARY = Indexes0.T_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index JPA_USER_PRIMARY = Internal.createIndex("PRIMARY", JpaUser.JPA_USER, new OrderField[] { JpaUser.JPA_USER.ID }, true);
        public static Index MEMBER_PRIMARY = Internal.createIndex("PRIMARY", Member.MEMBER, new OrderField[] { Member.MEMBER.ID }, true);
        public static Index STUDENT_PRIMARY = Internal.createIndex("PRIMARY", Student.STUDENT, new OrderField[] { Student.STUDENT.ID }, true);
        public static Index SYS_MENU_PRIMARY = Internal.createIndex("PRIMARY", SysMenu.SYS_MENU, new OrderField[] { SysMenu.SYS_MENU.MENU_ID }, true);
        public static Index SYS_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.ROLE_ID }, true);
        public static Index SYS_ROLE_MENU_PRIMARY = Internal.createIndex("PRIMARY", SysRoleMenu.SYS_ROLE_MENU, new OrderField[] { SysRoleMenu.SYS_ROLE_MENU.ID }, true);
        public static Index SYS_USER_PRIMARY = Internal.createIndex("PRIMARY", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.USER_ID }, true);
        public static Index SYS_USER_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.ID }, true);
        public static Index TB_USER_PRIMARY = Internal.createIndex("PRIMARY", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.ID }, true);
        public static Index T_PERMISSIONS_PRIMARY = Internal.createIndex("PRIMARY", TPermissions.T_PERMISSIONS, new OrderField[] { TPermissions.T_PERMISSIONS.ID }, true);
        public static Index T_ROLE_PRIMARY = Internal.createIndex("PRIMARY", TRole.T_ROLE, new OrderField[] { TRole.T_ROLE.ID }, true);
        public static Index T_USER_PRIMARY = Internal.createIndex("PRIMARY", TUser.T_USER, new OrderField[] { TUser.T_USER.ID }, true);
    }
}
