/*
 * This file is generated by jOOQ.
 */
package com.test.entity;


import com.test.entity.tables.JpaUser;
import com.test.entity.tables.Member;
import com.test.entity.tables.Student;
import com.test.entity.tables.SysMenu;
import com.test.entity.tables.SysRole;
import com.test.entity.tables.SysRoleMenu;
import com.test.entity.tables.SysUser;
import com.test.entity.tables.SysUserRole;
import com.test.entity.tables.TPermissions;
import com.test.entity.tables.TRole;
import com.test.entity.tables.TUser;
import com.test.entity.tables.TbUser;
import com.test.entity.tables.records.JpaUserRecord;
import com.test.entity.tables.records.MemberRecord;
import com.test.entity.tables.records.StudentRecord;
import com.test.entity.tables.records.SysMenuRecord;
import com.test.entity.tables.records.SysRoleMenuRecord;
import com.test.entity.tables.records.SysRoleRecord;
import com.test.entity.tables.records.SysUserRecord;
import com.test.entity.tables.records.SysUserRoleRecord;
import com.test.entity.tables.records.TPermissionsRecord;
import com.test.entity.tables.records.TRoleRecord;
import com.test.entity.tables.records.TUserRecord;
import com.test.entity.tables.records.TbUserRecord;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JpaUserRecord, Long> IDENTITY_JPA_USER = Identities0.IDENTITY_JPA_USER;
    public static final Identity<MemberRecord, Integer> IDENTITY_MEMBER = Identities0.IDENTITY_MEMBER;
    public static final Identity<StudentRecord, Integer> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<SysMenuRecord, Long> IDENTITY_SYS_MENU = Identities0.IDENTITY_SYS_MENU;
    public static final Identity<SysRoleRecord, Long> IDENTITY_SYS_ROLE = Identities0.IDENTITY_SYS_ROLE;
    public static final Identity<SysRoleMenuRecord, Long> IDENTITY_SYS_ROLE_MENU = Identities0.IDENTITY_SYS_ROLE_MENU;
    public static final Identity<SysUserRecord, Long> IDENTITY_SYS_USER = Identities0.IDENTITY_SYS_USER;
    public static final Identity<SysUserRoleRecord, Long> IDENTITY_SYS_USER_ROLE = Identities0.IDENTITY_SYS_USER_ROLE;
    public static final Identity<TbUserRecord, Long> IDENTITY_TB_USER = Identities0.IDENTITY_TB_USER;
    public static final Identity<TUserRecord, Integer> IDENTITY_T_USER = Identities0.IDENTITY_T_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JpaUserRecord> KEY_JPA_USER_PRIMARY = UniqueKeys0.KEY_JPA_USER_PRIMARY;
    public static final UniqueKey<MemberRecord> KEY_MEMBER_PRIMARY = UniqueKeys0.KEY_MEMBER_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<SysMenuRecord> KEY_SYS_MENU_PRIMARY = UniqueKeys0.KEY_SYS_MENU_PRIMARY;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PRIMARY;
    public static final UniqueKey<SysRoleMenuRecord> KEY_SYS_ROLE_MENU_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_MENU_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = UniqueKeys0.KEY_SYS_USER_PRIMARY;
    public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_USER_ROLE_PRIMARY;
    public static final UniqueKey<TbUserRecord> KEY_TB_USER_PRIMARY = UniqueKeys0.KEY_TB_USER_PRIMARY;
    public static final UniqueKey<TPermissionsRecord> KEY_T_PERMISSIONS_PRIMARY = UniqueKeys0.KEY_T_PERMISSIONS_PRIMARY;
    public static final UniqueKey<TRoleRecord> KEY_T_ROLE_PRIMARY = UniqueKeys0.KEY_T_ROLE_PRIMARY;
    public static final UniqueKey<TUserRecord> KEY_T_USER_PRIMARY = UniqueKeys0.KEY_T_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<JpaUserRecord, Long> IDENTITY_JPA_USER = Internal.createIdentity(JpaUser.JPA_USER, JpaUser.JPA_USER.ID);
        public static Identity<MemberRecord, Integer> IDENTITY_MEMBER = Internal.createIdentity(Member.MEMBER, Member.MEMBER.ID);
        public static Identity<StudentRecord, Integer> IDENTITY_STUDENT = Internal.createIdentity(Student.STUDENT, Student.STUDENT.ID);
        public static Identity<SysMenuRecord, Long> IDENTITY_SYS_MENU = Internal.createIdentity(SysMenu.SYS_MENU, SysMenu.SYS_MENU.MENU_ID);
        public static Identity<SysRoleRecord, Long> IDENTITY_SYS_ROLE = Internal.createIdentity(SysRole.SYS_ROLE, SysRole.SYS_ROLE.ROLE_ID);
        public static Identity<SysRoleMenuRecord, Long> IDENTITY_SYS_ROLE_MENU = Internal.createIdentity(SysRoleMenu.SYS_ROLE_MENU, SysRoleMenu.SYS_ROLE_MENU.ID);
        public static Identity<SysUserRecord, Long> IDENTITY_SYS_USER = Internal.createIdentity(SysUser.SYS_USER, SysUser.SYS_USER.USER_ID);
        public static Identity<SysUserRoleRecord, Long> IDENTITY_SYS_USER_ROLE = Internal.createIdentity(SysUserRole.SYS_USER_ROLE, SysUserRole.SYS_USER_ROLE.ID);
        public static Identity<TbUserRecord, Long> IDENTITY_TB_USER = Internal.createIdentity(TbUser.TB_USER, TbUser.TB_USER.ID);
        public static Identity<TUserRecord, Integer> IDENTITY_T_USER = Internal.createIdentity(TUser.T_USER, TUser.T_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<JpaUserRecord> KEY_JPA_USER_PRIMARY = Internal.createUniqueKey(JpaUser.JPA_USER, "KEY_jpa_user_PRIMARY", JpaUser.JPA_USER.ID);
        public static final UniqueKey<MemberRecord> KEY_MEMBER_PRIMARY = Internal.createUniqueKey(Member.MEMBER, "KEY_member_PRIMARY", Member.MEMBER.ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = Internal.createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.ID);
        public static final UniqueKey<SysMenuRecord> KEY_SYS_MENU_PRIMARY = Internal.createUniqueKey(SysMenu.SYS_MENU, "KEY_sys_menu_PRIMARY", SysMenu.SYS_MENU.MENU_ID);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = Internal.createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_PRIMARY", SysRole.SYS_ROLE.ROLE_ID);
        public static final UniqueKey<SysRoleMenuRecord> KEY_SYS_ROLE_MENU_PRIMARY = Internal.createUniqueKey(SysRoleMenu.SYS_ROLE_MENU, "KEY_sys_role_menu_PRIMARY", SysRoleMenu.SYS_ROLE_MENU.ID);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = Internal.createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_PRIMARY", SysUser.SYS_USER.USER_ID);
        public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = Internal.createUniqueKey(SysUserRole.SYS_USER_ROLE, "KEY_sys_user_role_PRIMARY", SysUserRole.SYS_USER_ROLE.ID);
        public static final UniqueKey<TbUserRecord> KEY_TB_USER_PRIMARY = Internal.createUniqueKey(TbUser.TB_USER, "KEY_tb_user_PRIMARY", TbUser.TB_USER.ID);
        public static final UniqueKey<TPermissionsRecord> KEY_T_PERMISSIONS_PRIMARY = Internal.createUniqueKey(TPermissions.T_PERMISSIONS, "KEY_t_permissions_PRIMARY", TPermissions.T_PERMISSIONS.ID);
        public static final UniqueKey<TRoleRecord> KEY_T_ROLE_PRIMARY = Internal.createUniqueKey(TRole.T_ROLE, "KEY_t_role_PRIMARY", TRole.T_ROLE.ID);
        public static final UniqueKey<TUserRecord> KEY_T_USER_PRIMARY = Internal.createUniqueKey(TUser.T_USER, "KEY_t_user_PRIMARY", TUser.T_USER.ID);
    }
}
