/*
 * This file is generated by jOOQ.
 */
package com.test.entity;


import com.test.entity.tables.JpaUser;
import com.test.entity.tables.Member;
import com.test.entity.tables.Student;
import com.test.entity.tables.SysMenu;
import com.test.entity.tables.SysRole;
import com.test.entity.tables.SysRoleMenu;
import com.test.entity.tables.SysUser;
import com.test.entity.tables.SysUserRole;
import com.test.entity.tables.TPermissions;
import com.test.entity.tables.TRole;
import com.test.entity.tables.TUser;
import com.test.entity.tables.TbUser;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.jpa_user</code>.
     */
    public static final JpaUser JPA_USER = JpaUser.JPA_USER;

    /**
     * The table <code>test.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>test.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * 权限表
     */
    public static final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * 角色表
     */
    public static final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * 角色与权限关系表
     */
    public static final SysRoleMenu SYS_ROLE_MENU = SysRoleMenu.SYS_ROLE_MENU;

    /**
     * 系统用户表
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * 用户与角色关系表
     */
    public static final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;

    /**
     * The table <code>test.tb_user</code>.
     */
    public static final TbUser TB_USER = TbUser.TB_USER;

    /**
     * The table <code>test.t_permissions</code>.
     */
    public static final TPermissions T_PERMISSIONS = TPermissions.T_PERMISSIONS;

    /**
     * The table <code>test.t_role</code>.
     */
    public static final TRole T_ROLE = TRole.T_ROLE;

    /**
     * The table <code>test.t_user</code>.
     */
    public static final TUser T_USER = TUser.T_USER;
}
