/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.records;


import com.test.entity.tables.JpaUser;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JpaUserRecord extends UpdatableRecordImpl<JpaUserRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = -130175648;

    /**
     * Setter for <code>test.jpa_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.jpa_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.jpa_user.user_mobile</code>.
     */
    public void setUserMobile(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.jpa_user.user_mobile</code>.
     */
    public String getUserMobile() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.jpa_user.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.jpa_user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return JpaUser.JPA_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return JpaUser.JPA_USER.USER_MOBILE;
    }

    @Override
    public Field<String> field3() {
        return JpaUser.JPA_USER.USER_NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserMobile();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserMobile();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public JpaUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public JpaUserRecord value2(String value) {
        setUserMobile(value);
        return this;
    }

    @Override
    public JpaUserRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public JpaUserRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JpaUserRecord
     */
    public JpaUserRecord() {
        super(JpaUser.JPA_USER);
    }

    /**
     * Create a detached, initialised JpaUserRecord
     */
    public JpaUserRecord(Long id, String userMobile, String userName) {
        super(JpaUser.JPA_USER);

        set(0, id);
        set(1, userMobile);
        set(2, userName);
    }
}
