/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.records;


import com.test.entity.tables.SysMenu;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuRecord extends UpdatableRecordImpl<SysMenuRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = -84797037;

    /**
     * Setter for <code>test.sys_menu.menu_id</code>. 权限ID
     */
    public void setMenuId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.sys_menu.menu_id</code>. 权限ID
     */
    public Long getMenuId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.sys_menu.name</code>. 权限名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.sys_menu.name</code>. 权限名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.sys_menu.perms</code>. 权限标识
     */
    public void setPerms(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.sys_menu.perms</code>. 权限标识
     */
    public String getPerms() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysMenu.SYS_MENU.MENU_ID;
    }

    @Override
    public Field<String> field2() {
        return SysMenu.SYS_MENU.NAME;
    }

    @Override
    public Field<String> field3() {
        return SysMenu.SYS_MENU.PERMS;
    }

    @Override
    public Long component1() {
        return getMenuId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPerms();
    }

    @Override
    public Long value1() {
        return getMenuId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPerms();
    }

    @Override
    public SysMenuRecord value1(Long value) {
        setMenuId(value);
        return this;
    }

    @Override
    public SysMenuRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SysMenuRecord value3(String value) {
        setPerms(value);
        return this;
    }

    @Override
    public SysMenuRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysMenuRecord
     */
    public SysMenuRecord() {
        super(SysMenu.SYS_MENU);
    }

    /**
     * Create a detached, initialised SysMenuRecord
     */
    public SysMenuRecord(Long menuId, String name, String perms) {
        super(SysMenu.SYS_MENU);

        set(0, menuId);
        set(1, name);
        set(2, perms);
    }
}
