/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.records;


import com.test.entity.tables.SysRole;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleRecord extends UpdatableRecordImpl<SysRoleRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -359663305;

    /**
     * Setter for <code>test.sys_role.role_id</code>. 角色ID
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.sys_role.role_id</code>. 角色ID
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.sys_role.role_name</code>. 角色名称
     */
    public void setRoleName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.sys_role.role_name</code>. 角色名称
     */
    public String getRoleName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysRole.SYS_ROLE.ROLE_ID;
    }

    @Override
    public Field<String> field2() {
        return SysRole.SYS_ROLE.ROLE_NAME;
    }

    @Override
    public Long component1() {
        return getRoleId();
    }

    @Override
    public String component2() {
        return getRoleName();
    }

    @Override
    public Long value1() {
        return getRoleId();
    }

    @Override
    public String value2() {
        return getRoleName();
    }

    @Override
    public SysRoleRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SysRoleRecord value2(String value) {
        setRoleName(value);
        return this;
    }

    @Override
    public SysRoleRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleRecord
     */
    public SysRoleRecord() {
        super(SysRole.SYS_ROLE);
    }

    /**
     * Create a detached, initialised SysRoleRecord
     */
    public SysRoleRecord(Long roleId, String roleName) {
        super(SysRole.SYS_ROLE);

        set(0, roleId);
        set(1, roleName);
    }
}
