/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.records;


import com.test.entity.tables.SysUserRole;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户与角色关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRoleRecord extends UpdatableRecordImpl<SysUserRoleRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -2084722437;

    /**
     * Setter for <code>test.sys_user_role.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.sys_user_role.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.sys_user_role.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.sys_user_role.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>test.sys_user_role.role_id</code>. 角色ID
     */
    public void setRoleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.sys_user_role.role_id</code>. 角色ID
     */
    public Long getRoleId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysUserRole.SYS_USER_ROLE.ID;
    }

    @Override
    public Field<Long> field2() {
        return SysUserRole.SYS_USER_ROLE.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return SysUserRole.SYS_USER_ROLE.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getRoleId();
    }

    @Override
    public SysUserRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value3(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRoleRecord
     */
    public SysUserRoleRecord() {
        super(SysUserRole.SYS_USER_ROLE);
    }

    /**
     * Create a detached, initialised SysUserRoleRecord
     */
    public SysUserRoleRecord(Long id, Long userId, Long roleId) {
        super(SysUserRole.SYS_USER_ROLE);

        set(0, id);
        set(1, userId);
        set(2, roleId);
    }
}
