/*
 * This file is generated by jOOQ.
 */
package com.test.entity.tables.records;


import com.test.entity.tables.TUser;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends UpdatableRecordImpl<TUserRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -2060138049;

    /**
     * Setter for <code>test.t_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.t_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.t_user.user_name</code>. 用户名
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.t_user.user_name</code>. 用户名
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.t_user.pass_word</code>. 密码
     */
    public void setPassWord(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.t_user.pass_word</code>. 密码
     */
    public String getPassWord() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TUser.T_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return TUser.T_USER.USER_NAME;
    }

    @Override
    public Field<String> field3() {
        return TUser.T_USER.PASS_WORD;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public String component3() {
        return getPassWord();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public String value3() {
        return getPassWord();
    }

    @Override
    public TUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public TUserRecord value3(String value) {
        setPassWord(value);
        return this;
    }

    @Override
    public TUserRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRecord
     */
    public TUserRecord() {
        super(TUser.T_USER);
    }

    /**
     * Create a detached, initialised TUserRecord
     */
    public TUserRecord(Integer id, String userName, String passWord) {
        super(TUser.T_USER);

        set(0, id);
        set(1, userName);
        set(2, passWord);
    }
}
